baseURL = 'https://miitaligupta.github.io/portfolio'
languageCode = 'en-us'
relativeURLs = "True"
title = "Mitali Gupta"
theme="hugoprofile1"

Paginate = 3


[markup.goldmark.renderer]
unsafe = true

[params]
title = "Mitali Gupta"
description = "Text about my cool site"
favicon = "/fav.png"
useBootstrapCDN = false
animate = true

  [params.theme]
  disableThemeToggle = false

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Mitali."
  subtitle = "I develop things"
  content = "I am passionate about building excellent software that improves the lives of those around me."
  # image = "/images/hero.svg"
  image = "https://hugo-profile.netlify.app/images/hero.svg"

    [params.hero.button]
    enable = true
    name = "Resume"
    url = "https://drive.google.com/file/d/1rEpf70uAVyhFyysgoxTkfrNfoC2hIsqo/view?usp=sharing"
    download = true

    [[params.hero.socialLinks.fontAwesomeIcons]]
    icon = "fab fa-github"
    url = "https://github.com/MiitaliGupta"

    [[params.hero.socialLinks.fontAwesomeIcons]]
    icon = "fab fa-linkedin"
    url = "https://www.linkedin.com/in/gupta-mitali/"



  [params.about]
  enable = true
  title = "About Me"
  # image = "/images/me.png"
  image = "https://hugo-profile.netlify.app/images/me.png"
  content = """
I am currently pursuing Bachelor's of Computer Applications at the [CHRIST University](https://christuniversity.in/), Bangalore.

Intrigued by design, traveling, technology, strategy, philosophy, fabulous food, and animals.

Seeking to be inspired, to envision the unlikely, to work hard for things that are worth it, and to be surrounded by those who bring out the best in me."""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = [ "Java", "Python","C",".Net (C#)","HTML","XML","CSS", "JavaScript", "PHP","MySQL", "Firebase","AWS","Git"]

  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "WordPress Developer Intern"
    company = "Suventure"
    companyUrl = "https://suventure.in/"
    date = "Jul 2021 - Aug 2021"
    content = "During this internship, I worked under the direct supervision of WordPress developer and contributed to team projects mainly in designing frontend of websites using WordPress and Elementor"

      [params.experience.items.featuredLink]
      enable = true
      name = "View the project"
      url = "https://shycocancorp.com/partners/"



    [[params.experience.items]]
    job = "Digital Marketing Intern"
    company = "International Model United Nation"
    companyUrl = "https://www.internationalmun.org/"
    date = "Jun 2021 - Jul 2021"
    content = """
During this internship, my work was mainly focused on determining keywords, posting content, checking web content, executing digital marketing campaigns, growing social media communities, and generating awareness of the organization’s existence across various social media platforms.
"""

  [params.education]
  enable = true

    [[params.education.items]]
    title = "Bachelor's of Computer Application"
    date = "2020 - 2023"
    GPA = "3.89 out of 4.0"
    content = """
      Positions of Responsibility
      - Student Coordinator, Labyrinth (Computer Science Club) (Aug’20 - Sept’22)

        - Appointed as a Core Committee member (Jul’22 - Sept’22)
        - Organized and managed various Conferences, Tech Talks, Workshops, and Competitions on Intra-Department, Inter-department, Intra-University, Inter-University and National Levels

      - Core Member, WRIT (Women in Research and IT) (Aug’21 - Present)

        - Appointed as a Core Committee member for academic year 2021 to 2023
        - Building a community for women in the technical field"""

      [params.education.items.school]
      name = "CHRIST University"
      url = "https://christuniversity.in/"

    [[params.education.items]]
    title = "Senior Secondary School (12th)"
    date = "2020"
    GPA = "93.70%"
    content = """
      Extra-Curricular Activities and Achievements
      - Elected Head Girl
      - State Level Participation (as team captain) in Kho-Kho, Throwball, Athletics
      """

            [params.education.items.school]
            name = "Carmel School"
            url = "http://carmelschoolgorakhpur.com/"

          [[params.education.items]]
          title = "High School (10th)"
          date = "2018"
          GPA = "92.80%"
          content = """
      Extra-Curricular Activities and Achievements
      - City Champion in International English Olympiad (IEO)
      - Debate Team Member (School Level)
      """

      [params.education.items.school]
      name = "Carmel Scool"
      url = "http://carmelschoolgorakhpur.com/"

  [params.achievements]
  enable = true

    [[params.achievements.items]]
    title = "AWS Academy: Cloud Foundations"

    [[params.achievements.items]]
    title = "AWS Academy: Machine Learning Foundation"

    [[params.achievements.items]]
    title = " Infosys Springboard: Explore Machine Learning Using Python"

    [[params.achievements.items]]
    title = "Infosys Springboard: Software Engineering and Agile Software Development"

    [[params.achievements.items]]
    title = "Internshala: Ethical Hacking"

    [[params.achievements.items]]
    title = "Swayam: German I"

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Petlet | Mobile Application"
    content = "A simple Pet Info Manaaging Application built on Android Studio using Java, XML and Firebase"
    # image = "{{ .Site.BaseURL }}/images/projects/profile.png"
    image = "https://hugo-profile.netlify.app/images/projects/profile.png"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/MiitaliGupta/Petlet"


    [[params.projects.items]]
    title = "Accio | Mobile Application"
    content = "A Lost and Found Application built on Android Studio using Java, XML and Firebase"
    # image = "{{ .Site.BaseURL }}/images/projects/profile.png"
    image = "https://hugo-profile.netlify.app/images/projects/converter.jpg"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/MiitaliGupta/Accio"

    [[params.projects.items]]
    title = "Astronomical Prediction Model | Machine Learning"
    content = "ML based model to Determine whether an Astronomical Body is Hazardous or not using the NASA’s dataset of Celestial Bodies containing its Relative Diameter and Velocity. It uses the concept of KNN Classification, Naive Bayes Classification and K-Mean Clustering, and python libraries including NumPy, Pandas, Sklearn, Seaborn, Matplotlib"
    image = "https://raw.githubusercontent.com/gurusabarish/hugo-profile/master/exampleSite/static/images/projects/profile2.jpg"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://bit.ly/KNN_graphs"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://bit.ly/NaiveBayes_new"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://bit.ly/KMeanClustering"

      [[params.projects.items]]
      title = "Altruists | Database Management"
      content = " NGO Management Multifunctional Website for the overall administration. The website also closely deals with APIs, including payment gateway, chatbot, GPS, and other state-of the-art technologies, It is built using HTML, CSS, JavaScript, PHP, MySQL"
      image = "https://raw.githubusercontent.com/gurusabarish/hugo-profile/master/exampleSite/static/images/projects/profile2.jpg"

      [params.projects.items.featured]
      name = "Demo"
      link = "https://altruists.herokuapp.com/"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/MiitaliGupta/Altruists"

      [[params.projects.items]]
      title = "Shycocan Corporation | Website Frontend"
      content = "Website for the product “Shycocan”, a life-saving Virus Attenuation Device that effectively disables the Coronavirus, built majorly using Elementor (WordPress) whilst interning at Suventure in a WebDev team"
      image = "https://raw.githubusercontent.com/gurusabarish/hugo-profile/master/exampleSite/static/images/projects/profile2.jpg"

      [params.projects.items.featured]
      name = "Demo"
      link = "https://shycocancorp.com/partners/"



      [[params.projects.items]]
      title = "Animal Alcove | Desktop Application"
      content = "An Application for Pet Shop/ Adoption Centre Employees and Customers, It is built on .NET framework using C# and MySQL"
      image = "https://raw.githubusercontent.com/gurusabarish/hugo-profile/master/exampleSite/static/images/projects/profile2.jpg"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/MiitaliGupta/AnimalAlcove"


  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  email = "miitali.gupta@gmail.com"
  btnName = "Mail me"

[params.footer.socialNetworks]
github = "https://github.com/MiitaliGupta"
linkedin = "https://www.linkedin.com/in/gupta-mitali/"
instagram = "https://www.instagram.com/m_i_talli/"
facebook = "https://www.facebook.com/mitali.gupta.3133"
